### ISSUE TITLE
[BUG] Fails to render the specification if it contains oauth2 security scheme with password flow

### ISSUE THREAD

**Issue by pltod2** [asyncapi/asyncapi-react#1007]
**Description**

When the specification contains securityScheme of type oauth2 that contains password flow and that scheme is referred in the document the spec fails to render. It happens in all the major browsers.

**Expected result**

The specification must be rendered successfully.

**Actual result**

The specification is not rendered, we get blank screen instead.

**Steps to reproduce**

The fastest way to reproduce is in async api studio which uses this component under the hood.
Add the following under components/securitySchemes:

```
    oauth2Password:
      type: oauth2
      description: OAuth 2.0 example
      flows:
        password:
          tokenUrl: https://auth.example.com/oauth/token
          refreshUrl: https://auth.example.com
          availableScopes:
            read:user: Read user information
```

Just adding the scheme is ok but if we further refer the scheme it will result in browser rendering a blank page. The error that can be seen in the console is:

<img width="539" alt="Screenshot 2024-05-29 at 10 54 39" src="https://github.com/asyncapi/asyncapi-react/assets/20239625/974a5b1d-66d8-4671-b7fa-92ecd55a32b9">

**Troubleshooting**

[As described in the spec](https://www.asyncapi.com/docs/reference/specification/v3.0.0#oauthFlowObject) the authorizationUrl does not apply to password flow.

However [in the code it is handled](https://github.com/asyncapi/asyncapi-react/blob/master/library/src/containers/Servers/Security.tsx#L171) as always present, which causes "undefined is not an object (evaluating 'i.authorizationUrl')" error.
