### ISSUE TITLE
Hide Message ID block if messageId is not set

### ISSUE THREAD

**Issue by Vaniog** [asyncapi/asyncapi-react#1049]
**Description**

Remove block [Message ID] presented on the photo, if message has no property "messageId" (as in attached specification)

**Reasons**

This duplicate information and take a lot of space

**Attachments**

```yaml
asyncapi: 3.0.0
info:
  title: Hello world application
  version: '0.1.0'
channels:
  hello:
    address: 'hello'
    messages:
      sayHelloMessage:
        payload:
          type: string
operations:
  receiveHello:
    action: 'receive'
    channel:
      $ref: '#/channels/hello'
```

![image](https://github.com/user-attachments/assets/43b21250-baa6-47d2-99cd-9683ec3e9035)

**Comment by ItshMoh** [comment]
Hey @Vaniog can you explain what are you trying to say in the issue. As the spec you have shared is containing the {messagId} 
. For this doc it is 'sayHelloMessage' . You can refer [here](https://www.asyncapi.com/docs/reference/specification/v3.0.0#messagesObject). 
let me know what are your thoughts.

**Comment by Vaniog** [comment]
In this case messageId is same as message name. But you can set `messageId` property, as in spec below.
```
components:
  messages:
    sayHelloMessage:
      messageId: notSayHelloMessage
      payload:
        type: object
        properties:
          name:
            type: string
```
And message name and messageId will be different
In case, which i provide in issue, these properties are same, so i dont want to see both of them in message header (screenshot)
