### ISSUE TITLE
Display message names in "Channels"

### ISSUE THREAD

**Issue by neherim** [asyncapi/asyncapi-react#140]
**Description**
Display message names or/and titles in "Channels"

**Reasons**
It is difficult to understand what message the channel is receiving, because only message payload and headers is displayed.
I think it would be more informative to display the name of the message itself instead of numbers or the title "Message".

**Attachments**

![image](https://user-images.githubusercontent.com/6769652/93525331-88679600-f93e-11ea-92e6-37bc25e7bb09.png)

**Comment by derberg** [comment]
@neherim could you please share some example asyncapi doc you work with? I assume you are using `oneOf`?

**Comment by neherim** [comment]
Yes you're right it's `oneOf`:

```yml
asyncapi: 2.0.0
info:
  title: Example project
  version: 1.0.0
servers:
  kafka:
    url: kafka:29092
    protocol: kafka
channels:
  another-topic:
    subscribe:
      message:
        oneOf:
        - name: io.github.stavshamir.springwolf.example.dtos.ExamplePayloadDto
          title: ExamplePayloadDto
          payload:
            "$ref": "#/components/schemas/ExamplePayloadDto"
        - name: io.github.stavshamir.springwolf.example.dtos.AnotherPayloadDto
          title: AnotherPayloadDto
          payload:
            "$ref": "#/components/schemas/AnotherPayloadDto"
  example-topic:
    subscribe:
      message:
        name: io.github.stavshamir.springwolf.example.dtos.ExamplePayloadDto
        title: ExamplePayloadDto
        payload:
          "$ref": "#/components/schemas/ExamplePayloadDto"
components:
  schemas:
    ExamplePayloadDto:
      type: object
      properties:
        someString:
          type: string
        someLong:
          type: integer
          format: int64
        someEnum:
          type: string
          enum:
          - FOO1
          - FOO2
          - FOO3
      example:
        someString: string
        someLong: 0
        someEnum: FOO1
    AnotherPayloadDto:
      type: object
      properties:
        foo:
          type: string
        example:
          "$ref": "#/components/schemas/ExamplePayloadDto"
      example:
        foo: string
        example:
          someString: string
          someLong: 0
          someEnum: FOO1
```

And I want to render this doc something like that:

![image](https://user-images.githubusercontent.com/6769652/94056216-acb3ee80-fde6-11ea-9ba3-175df0153ef0.png)
