### ISSUE TITLE
standalone bundle - styling issue - font

### ISSUE THREAD

**Issue by thim81** [asyncapi/asyncapi-react#530]
**Description**

When using the latest standalone bundle (`react-component@1.0.0-next.31`) in a HTML page, it seems that something is missing in the styling of the page.

**Expected result**

![2022-01-24 at 17 02 39](https://user-images.githubusercontent.com/952446/150818707-7cbfdb37-d88b-42eb-a2e2-fdc32a482e30.png)

**Actual result**

The font styling seems off.

![2022-01-24 at 17 03 29](https://user-images.githubusercontent.com/952446/150818827-695f77b9-ffd5-4f31-b9ea-c7ac9e46c781.png)

**Steps to reproduce**

You can use the HTML below to reproduce the styling issue

I'm using a standalone HTML implementation

```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>AsyncAPI Reference</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://unpkg.com/@asyncapi/react-component@1.0.0-next.32/styles/default.min.css">
</head>
<body>

<div id="asyncapi"></div>

<script src="https://unpkg.com/@asyncapi/react-component@1.0.0-next.32/browser/standalone/index.js"></script>
<script>
    AsyncApiStandalone.render({
        schema: {
            url: '../spec/smc.asyncapi.yaml',
            options: { method: "GET", mode: "cors" },
        },
        config: {
            show: {
                sidebar: true,
            }
        },
    }, document.getElementById('asyncapi'));
</script>

</body>
</html>

```

**Comment by thim81** [comment]
@magicmatatjahu I added something similar as work-around, but I wasn't sure if that was expected behaviour, but now I do :-) Thanks for clarifying.

The font-family and html/body margins/lineheights are the only CSS differences, that are left out?

**Comment by magicmatatjahu** [comment]
@thim81 We exactly used that file https://meyerweb.com/eric/tools/css/reset/ so you can check what exactly we "removed" + of course global font-family :) 

I think that we should clarify that in the docs, do you wanna create PR with that? :)

**Comment by thim81** [comment]
I ll create PR to document this. Shall I add on the main readme or do you prefer that I put it on a dedicated page for the standalone bundle?

**Comment by magicmatatjahu** [comment]
@thim81 

> I ll create PR to document this. Shall I add on the main readme or do you prefer that I put it on a dedicated page for the standalone bundle?

Please add in the Readme in the section when we describe styling https://github.com/asyncapi/asyncapi-react/tree/next#styles Remember about contribution to the `next` branch :)

**Comment by thim81** [comment]
@magicmatatjahu I also applied a "hack" CSS to inject a logo placeholder, is this something you think is valuable to include in the "styling" section?

Example:

```css
 <style>
        div.sidebar::before {
            background-color:#00b8fb;
            background-image: url(./logo.png');
            background-size: cover;
            background-position: center;
            display: inline-block;
            width: 17rem;
            height: 11rem;
            content:"";
        }
    </style>
```

Resulting in something like this:
![2022-01-25 at 10 31 35](https://user-images.githubusercontent.com/952446/150950183-a732de62-88e6-441b-8658-d2f0b6441637.png)

(I'm not CSS expert so if you have suggestions to handle this more gracefully, feel free to share)
