### ISSUE TITLE
Show schemas from external files in the sidebar

### ISSUE THREAD

**Issue by kennethaasan** [asyncapi/asyncapi-react#631]
**Show schemas from external files in the sidebar**

I'm trying to create messages and schemas in multiple files, and importing the files into the main AsyncAPI file:

AsyncAPI.yaml
```
asyncapi: "2.3.0"
info:
  title: Test
servers: {}
defaultContentType: application/json
channels: {}
components:
  messages:
    TestMessage:
      name: TestMessage
      payload:
        $ref: "./TestSchema.yaml#/components/schemas/TestSchema"
```

TestSchema.yaml
```
asyncapi: "2.3.0"
components:
  schemas:
    TestSchema:
      type: object
      properties:
        test:
          type: string
```

It works well, except that the sidebar doesn't show the TestSchema schema. Is that a bug, or expected because I'm referring to an external file? Our AsyncAPI file will be too big if we can't split our specification into multiple files, so I need to find a solution for this.
