### ISSUE TITLE
Manual examples do not work

### ISSUE THREAD

**Issue by matwojcik** [asyncapi/asyncapi-react#92]
**Description**

Manually provided examples of messages do not seem to be supported. Examples property of message:

https://www.asyncapi.com/docs/specifications/2.0.0/#a-name-messageobject-a-message-object

**Expected result**

Example should be presented

**Actual result**
```
Error: Invalid AsyncAPI document

.channels['user/signedup'].subscribe.message should have required property '$ref': $ref.channels['user/signedup'].subscribe.message should NOT have additional properties: description.channels['user/signedup'].subscribe.message should NOT have additional properties: examples.channels['user/signedup'].subscribe.message should NOT have additional properties: payload.channels['user/signedup'].subscribe.message should have required property 'oneOf': oneOf.channels['user/signedup'].subscribe.message.examples should be array.channels['user/signedup'].subscribe.message should match exactly one schema in oneOf: null.channels['user/signedup'].subscribe.message should match exactly one schema in oneOf: null
```
**Steps to reproduce**

```yaml
asyncapi: '2.0.0'
info:
  title: Example
  version: 0.1.0
channels:
  user/signedup:
    subscribe:
      message:
        description: An event describing that a user just signed up.
        examples:
          example1:
            fullname: Mark
            email: xx@xxx.pl
            age: 18
        payload:
          type: object
          additionalProperties: false
          properties:
            fullName:
              type: string
            email:
              type: string
              format: email
            age:
              type: integer
              minimum: 18
```

**Troubleshooting**
