### ISSUE TITLE
oneOf not included inside of array

### ISSUE THREAD

**Issue by kennethaasan** [asyncapi/asyncapi-react#926]
**Description**

oneOf is not included inside of array.

**Expected result**

The oneOf part of the schema is visible inside arrays.

**Actual result**

![Screenshot 2024-02-28 at 15 41 00](https://github.com/asyncapi/asyncapi-react/assets/1437394/8eb86cf6-149b-428f-956a-a7f5d4d01b8d)

As you can see, when Game is used inside an array, it's missing the oneOf part (Adheres to Game.Regular and Or to Game.TieBreak).

**Steps to reproduce**

```yaml
asyncapi: 2.6.0
info:
  title: Test
  version: 1.0.0
channels: {}
components:
  messages:
    state:
      payload:
        title: State
        type: object
        properties:
          sets:
            title: Sets
            type: array
            items:
              title: Set
              type: object
              properties:
                games:
                  title: Games
                  type: array
                  items:
                    "$ref": "#/components/schemas/game"
          game:
            "$ref": "#/components/schemas/game"
  schemas:
    game:
      title: Game
      type: object
      discriminator: type
      properties:
        type:
          title: Game.Type
          type: string
          enum:
          - REGULAR
          - TIE_BREAK
      oneOf:
      - title: Game.Regular
        type: object
        properties:
          type:
            const: REGULAR
      - title: Game.TieBreak
        type: object
        properties:
          type:
            const: TIE_BREAK
```

**Troubleshooting**

I've already checked the parser, and I don't see any issues. And because this library with playground doesn't work on my Mac with node.js v18 I'm not able to make a PR...
